// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/swp391-group3/ai-interview-practice/api/internal/config"
	"github.com/swp391-group3/ai-interview-practice/api/internal/pkg/logger"
	"github.com/swp391-group3/ai-interview-practice/api/internal/pkg/tracer"
	"github.com/swp391-group3/ai-interview-practice/api/internal/provider"
	"github.com/swp391-group3/ai-interview-practice/api/internal/server"
)

// Injectors from wire.go:

func InitializeApplication(configPath string) (*Application, func(), error) {
	config, err := provider.ProvideConfig(configPath)
	if err != nil {
		return nil, nil, err
	}
	logger, cleanup, err := provider.ProvideLogger(config)
	if err != nil {
		return nil, nil, err
	}
	pool, cleanup2, err := provider.ProvideDatabasePool(config, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	queries := provider.ProvideAuthQueries(pool)
	authService := provider.ProvideAuthService(config, queries)
	authHandler := provider.ProvideAuthHandler(authService)
	healthHandler := provider.ProvideHealthHandler()
	engine := provider.ProvideRouter(config, logger, authHandler, healthHandler)
	server := provider.ProvideHTTPServer(config, engine, logger)
	tracer, cleanup3, err := provider.ProvideTracer(config, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	application := &Application{
		Server: server,
		Pool:   pool,
		Logger: logger,
		Tracer: tracer,
		Config: config,
	}
	return application, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type Application struct {
	Server *server.Server
	Pool   *pgxpool.Pool
	Logger *logger.Logger
	Tracer *tracer.Tracer
	Config *config.Config
}
