// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, password_hash, is_locked
FROM accounts
WHERE email = $1
`

type GetAccountByEmailRow struct {
	ID           uuid.UUID
	PasswordHash string
	IsLocked     bool
}

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (GetAccountByEmailRow, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i GetAccountByEmailRow
	err := row.Scan(&i.ID, &i.PasswordHash, &i.IsLocked)
	return i, err
}
