// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jd.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createJD = `-- name: CreateJD :one
INSERT INTO job_descriptions (user_id, title, seniority_level, raw_text, parsed_data, status)
VALUES ($1, $2, $3, $4, $5, 'customized')
RETURNING id, user_id, title, seniority_level, raw_text, parsed_data, status, created_at, updated_at
`

type CreateJDParams struct {
	UserID         uuid.UUID
	Title          string
	SeniorityLevel SeniorityLevel
	RawText        string
	ParsedData     []byte
}

func (q *Queries) CreateJD(ctx context.Context, arg CreateJDParams) (JobDescription, error) {
	row := q.db.QueryRow(ctx, createJD,
		arg.UserID,
		arg.Title,
		arg.SeniorityLevel,
		arg.RawText,
		arg.ParsedData,
	)
	var i JobDescription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.SeniorityLevel,
		&i.RawText,
		&i.ParsedData,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJD = `-- name: DeleteJD :one
DELETE FROM job_descriptions
WHERE id = $1 AND user_id = $2
RETURNING id
`

type DeleteJDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteJD(ctx context.Context, arg DeleteJDParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteJD, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getJD = `-- name: GetJD :one
SELECT id, user_id, title, seniority_level, raw_text, parsed_data, status, created_at, updated_at FROM job_descriptions
WHERE id = $1 AND user_id = $2
`

type GetJDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetJD(ctx context.Context, arg GetJDParams) (JobDescription, error) {
	row := q.db.QueryRow(ctx, getJD, arg.ID, arg.UserID)
	var i JobDescription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.SeniorityLevel,
		&i.RawText,
		&i.ParsedData,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJDs = `-- name: ListJDs :many
SELECT id, user_id, title, seniority_level, raw_text, parsed_data, status, created_at, updated_at FROM job_descriptions
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListJDs(ctx context.Context, userID uuid.UUID) ([]JobDescription, error) {
	rows, err := q.db.Query(ctx, listJDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobDescription
	for rows.Next() {
		var i JobDescription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.SeniorityLevel,
			&i.RawText,
			&i.ParsedData,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJD = `-- name: UpdateJD :one
UPDATE job_descriptions
SET title = $1, seniority_level = $2,
    parsed_data = $3, updated_at = now()
WHERE id = $4 AND user_id = $5
RETURNING id, user_id, title, seniority_level, raw_text, parsed_data, status, created_at, updated_at
`

type UpdateJDParams struct {
	Title          string
	SeniorityLevel SeniorityLevel
	ParsedData     []byte
	ID             uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) UpdateJD(ctx context.Context, arg UpdateJDParams) (JobDescription, error) {
	row := q.db.QueryRow(ctx, updateJD,
		arg.Title,
		arg.SeniorityLevel,
		arg.ParsedData,
		arg.ID,
		arg.UserID,
	)
	var i JobDescription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.SeniorityLevel,
		&i.RawText,
		&i.ParsedData,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
