// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type JdStatus string

const (
	JdStatusUploaded   JdStatus = "uploaded"
	JdStatusParsing    JdStatus = "parsing"
	JdStatusParsed     JdStatus = "parsed"
	JdStatusCustomized JdStatus = "customized"
	JdStatusLocked     JdStatus = "locked"
	JdStatusFailed     JdStatus = "failed"
)

func (e *JdStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JdStatus(s)
	case string:
		*e = JdStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JdStatus: %T", src)
	}
	return nil
}

type NullJdStatus struct {
	JdStatus JdStatus
	Valid    bool // Valid is true if JdStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJdStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JdStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JdStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJdStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JdStatus), nil
}

type SeniorityLevel string

const (
	SeniorityLevelIntern SeniorityLevel = "intern"
	SeniorityLevelJunior SeniorityLevel = "junior"
	SeniorityLevelMid    SeniorityLevel = "mid"
	SeniorityLevelSenior SeniorityLevel = "senior"
	SeniorityLevelLead   SeniorityLevel = "lead"
)

func (e *SeniorityLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SeniorityLevel(s)
	case string:
		*e = SeniorityLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for SeniorityLevel: %T", src)
	}
	return nil
}

type NullSeniorityLevel struct {
	SeniorityLevel SeniorityLevel
	Valid          bool // Valid is true if SeniorityLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSeniorityLevel) Scan(value interface{}) error {
	if value == nil {
		ns.SeniorityLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SeniorityLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSeniorityLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SeniorityLevel), nil
}

type JobDescription struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Title          string
	SeniorityLevel SeniorityLevel
	RawText        string
	ParsedData     []byte
	Status         JdStatus
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
